export const products = [
  {
    id: 1,
    slug: "casio-esfera-plateada-acero-inoxidable-cuarzo-41mm",
    name: "Casio Esfera Plateada Acero Inoxidable Cuarzo 41mm",
    model: "MTP-B195D",
    price: 599,
    category: "Premium",
    tag: "DESTACADO",
    description: "Reloj de cuarzo con esfera plateada y caja de acero inoxidable de 41mm. Diseño clásico y elegante para el hombre moderno.",
    features: ["Movimiento de cuarzo", "Caja acero inoxidable 41mm", "Resistente al agua", "Cristal mineral"],
    variants: [
      { color: "Plateado", label: "Plateado" },
      { color: "Plateado / Negro", label: "Plateado / Negro" },
      { color: "Plateado / Azul", label: "Plateado / Azul" },
      { color: "Plateado / Verde", label: "Plateado / Verde" },
      { color: "Correa Cuero Negro", label: "Correa Cuero Negro" },
      { color: "Correa Cuero / Verde", label: "Correa Cuero / Verde" },
    ],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/imgi_91_s-l1600.jpg?v=1776182864&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-esfera-plateada-acero-inoxidable-cuarzo-41-mm",
  },
  {
    id: 2,
    slug: "casio-vintage",
    name: "Casio Vintage",
    model: "Vintage Classic",
    price: 450,
    category: "Vintage",
    tag: "CLÁSICO",
    description: "El icónico Casio Vintage, símbolo de la cultura retro. Diseño atemporal que nunca pasa de moda.",
    features: ["Display digital", "Correa de resina", "Resistente al agua 30m", "Alarma y cronómetro"],
    variants: [],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at8.44.02PM.jpg?v=1776181537&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-vintage",
  },
  {
    id: 3,
    slug: "casio-clasic-mq-24d-7e-dorado",
    name: "Casio Clasic MQ-24D-7e Dorado",
    model: "MQ-24D-7E",
    price: 430,
    category: "Classic",
    tag: "POPULAR",
    description: "El clásico Casio MQ-24 en acabado dorado. Reloj analógico de cuarzo con diseño minimalista y elegante.",
    features: ["Movimiento analógico de cuarzo", "Caja dorada", "Correa de resina", "Resistente al agua 30m"],
    variants: [],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at8.44.02PM.jpg?v=1776181537&width=800",
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at8.44.24PM.jpg?v=1776181536&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-clasic-mq-24d-7e-dorado",
  },
  {
    id: 4,
    slug: "casio-collection-ltp-e117d-azul-dorado",
    name: "Casio Collection LTP-E117D Azul/Dorado",
    model: "LTP-E117D",
    price: 449,
    category: "Collection",
    tag: "NUEVO",
    description: "Reloj unisex de la colección LTP-E117D en combinación azul y dorado. Elegante y versátil para cualquier ocasión.",
    features: ["Unisex", "Esfera azul/dorado", "Caja dorada", "Resistente al agua"],
    variants: [
      { color: "Azul/Dorado", label: "Azul/Dorado" },
      { color: "Dorado Digital", label: "Dorado Digital" },
      { color: "Gris/Plateado", label: "Gris/Plateado" },
      { color: "Negro/Negro", label: "Negro/Negro" },
      { color: "Plateado Digital", label: "Plateado Digital" },
    ],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at9.50.47PM.jpg?v=1776181535&width=800",
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at8.44.24PM_5838bf23-5e22-4b32-916b-fe7a16eed764.jpg?v=1776181535&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-collection-ltp-e117d-reloj-unisex-para-adultos-azul-dorado-us-one-size",
  },
  {
    id: 5,
    slug: "casio-collection-ltp-e120-negro",
    name: "Casio Collection LTP-E120 Negro",
    model: "LTP-E120",
    price: 530,
    category: "Collection",
    tag: "BEST SELLER",
    description: "Reloj unisex LTP-E120 en negro. Diseño deportivo y elegante con acabados de alta calidad.",
    features: ["Unisex", "Esfera negra", "Caja negra", "Resistente al agua 30m"],
    variants: [
      { color: "Negro", label: "Negro" },
      { color: "Blanco/Dorado", label: "Blanco/Dorado" },
      { color: "Blanco/Plateado", label: "Blanco/Plateado" },
    ],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at9.58.48PM.jpg?v=1776181533&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-collection-ltp-e120-reloj-unisex-para-adultos-negro-us-one-size",
  },
  {
    id: 6,
    slug: "casio-g-shock-mtpb145dc21v",
    name: "Casio G-Shock MTPB145DC21V",
    model: "MTP-B145DC",
    price: 530,
    category: "G-SHOCK",
    tag: "G-SHOCK",
    description: "Reloj G-Shock con la resistencia y durabilidad que caracteriza a la línea más icónica de Casio. Diseñado para soportar las condiciones más exigentes.",
    features: ["Resistente a golpes", "Resistente al agua 200m", "Iluminación LED", "Alarma múltiple"],
    variants: [],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at8.44.24PM_7f83e25f-9555-4019-9fbd-04ff925c723d.jpg?v=1776181534&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-g-shock-mtpb145dc21v",
  },
  {
    id: 7,
    slug: "casio-modelo-mtp-1381-blanco-plata",
    name: "Casio Modelo Mtp-1381 Blanco Plata",
    model: "MTP-1381",
    price: 530,
    category: "Classic",
    tag: "ELEGANTE",
    description: "El clásico MTP-1381 en combinación blanco y plata. Reloj de cuarzo con diseño sobrio y elegante para el ejecutivo moderno.",
    features: ["Movimiento de cuarzo", "Esfera blanca", "Caja plateada", "Cristal mineral"],
    variants: [
      { color: "Blanco/Plata", label: "Blanco/Plata" },
    ],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at9.55.26PM.jpg?v=1776181534&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-modelo-mtp-1381-blanco-plata",
  },
  {
    id: 8,
    slug: "casio-modelo-mtp-1381-blanco-plata-acero",
    name: "Casio Mtp-1381 Blanco Plata Acero",
    model: "MTP-1381 Steel",
    price: 430,
    category: "Classic",
    tag: "OFERTA",
    description: "Versión en acero del MTP-1381. Pulsera de acero inoxidable con esfera blanca y plateada.",
    features: ["Pulsera de acero inoxidable", "Esfera blanca", "Cuarzo preciso", "Resistente al agua"],
    variants: [],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at8.44.24PM_115fbad0-cc50-4cb3-ad83-57de4f6e18c7.jpg?v=1776181533&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-modelo-mtp-1381-blanco-plata-acero",
  },
  {
    id: 9,
    slug: "casio-woman-ltp-1170n-9a",
    name: "CASIO Woman LTP-1170N-9A",
    model: "LTP-1170N-9A",
    price: 389,
    category: "Mujer",
    tag: "MUJER",
    description: "Reloj femenino LTP-1170N-9A. Diseño delicado y elegante especialmente pensado para la mujer moderna.",
    features: ["Colección mujer", "Diseño delicado", "Movimiento de cuarzo", "Resistente al agua 30m"],
    variants: [],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at8.44.02PM.jpg?v=1776181537&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-woman-ltp-1170n-9a",
  },
  {
    id: 10,
    slug: "casio-reloj-cuarzo-mtp-vt01",
    name: "Casio Reloj de Cuarzo MTP-VT01",
    model: "MTP-VT01",
    price: 425.50,
    category: "Classic",
    tag: "NUEVO",
    description: "Reloj de cuarzo de la serie MTP-VT01. Diseño moderno con funciones prácticas para el día a día.",
    features: ["Serie MTP-VT01", "Movimiento de cuarzo", "Diseño moderno", "Resistente al agua"],
    variants: [],
    images: [
      "https://casio-mexico.myshopify.com/cdn/shop/files/WhatsAppImage2024-06-30at8.44.24PM.jpg?v=1776181536&width=800",
    ],
    shopifyUrl: "https://casio-mexico.myshopify.com/products/casio-reloj-de-cuarzo-serie-mtp-vt01",
  },
];

export const categories = ["Todos", "G-SHOCK", "Premium", "Collection", "Classic", "Vintage", "Mujer"];

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category) {
  if (category === "Todos") return products;
  return products.filter((p) => p.category === category);
}
